@startuml
actor User

box Card game 
   participant Main
   participant Program
   participant Dealer
   participant Player
   participant Thread
end box

User -> Main: stars game
Main -> Program: new Program()
Main <-- Program: Program
Main -> Program: start()
Program -> Program: getPlayerCount()
Program --> User: "How many players? (2-4)"
User -> Program: n
Program -> Program: IntiGame(n)
Program -> Dealer: new Dealer()
Program <-- Dealer:  Dealer
loop n times
    Program -> Player:  new Player(Dealer)
    Program <-- Player:  Player
    loop 4 times
        Program -> Player: AddCardToHand()
    end
    Program -> Player: ShowHand()
    Player --> User: hand
end
loop n times
Program -> Program: MakeThread(Players[n-1])
Program -> Program: play(Player)
Program -> Program: thread.start
end
group while win = false
Thread -> Program: OneRound(player)
Program ->Player:AddCardToHand();                   
Program ->Player:RemoveCardFromHand()
Program ->Player:ShowHand()
Player --> User: hand
Program ->Player:SeeIfWins()
Thread -> Thread: Sleep(200)
end 
Program --> User: winner



@enduml